name: 'seven.io Voice'
author: 'seven communications GmbH & Co. KG'
description: 'Send Voice message through GitHub Actions via seven.io'
inputs:
  apiKey:
    description: 'A seven.io API Key. Alternatively stored in environment variable SEVEN_API_KEY'
    required: true
  from:
    description: 'Sender ID; A seven.io approved or shared number'
    required: false
  text:
    description: 'The actual message content you want to send to the recipient(s)'
    required: true
  to:
    description: 'Phone number'
    required: true

outputs:
  response:
    description: 'The API response'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  color: 'green'
  icon: 'message-square'
